name: Update latest status workflow
on:
  schedule: # Run workflow automatically
#     - cron: '0 * * * *' # Runs every hour, on the hou
    - cron: "0 0 * * *" # Runs at 12am UTC
  workflow_dispatch: # Run workflow manually with a trigger
jobs:
  # Update weekly activity
  update-readme:
    name: Update this repo's README with weekly activity
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.TOKEN }}
          SHOW_TIME: false
          SHOW_TITLE: true
          
  # Update blog posts
#   update-readme-with-blog:
#     name: Update this repo's README with latest blog posts
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: gautamkrishnar/blog-post-workflow@master
#         with:
#           # you can change this to your own RSS feed
#           feed_list: "https://www.hikariai.net/index.xml"
      
